### ISSUE TITLE
Feature request: make `EcoVec::new()` const

### ISSUE THREAD

**Issue by Kmeakin** [typst/ecow#27]
It would be nice if `EcoVec::new()` were callable in `const` contexts, to match `Vec::new()`

**Comment by laurmaedje** [comment]
Unfortunately, it is not possible in the current design because `EcoVec::new` depends on a static and const fns can't reference statics. 

`Vec` initializes its pointer with `NonNull::dangling` and uses its `capacity` to track whether it is initialized. `EcoVec` in comparison initializes its pointer with the address of a static `SENTINEL` value and uses that to track whether it is initialized. Using `NonNull::dangling` isn't possible because we have no other means to track whether we are initialized and `NonNull::dangling` _could_ be a valid to pointer to an allocation.

Null cannot be used in either case because a slice's pointer can't be null and we want deref to slice to be a no-op (that's a design goal).

**Comment by Kmeakin** [comment]
Could the sign bit in `len` be used as the allocated flag? Allocations of more than `isize::MAX` are not allowed in Rust, so could be used to signal `self.len > (isize::MAX as usize)` an unallocated `EcoVec`

**Comment by laurmaedje** [comment]
Then `EcoVec<T>`'s deref to `[T]` isn't a no-op once again. Moreover, `EcoString` (which uses `EcoVec` internally) uses that bit to [distinguish](https://github.com/typst/ecow/blob/9aa2b9ee6642d626db64c8043d0aa35928c755cd/src/dynamic.rs#L13) between inline and heap (`EcoVec<u8>`) representation.

**Comment by Kmeakin** [comment]
Possible implementation: https://github.com/typst/ecow/pull/28

**Comment by laurmaedje** [comment]
Implemented in https://github.com/typst/ecow/pull/28.

I'll publish a new release soon.

**Comment by flyingmutant** [comment]
Sorry for the ping, any news about the release?

**Comment by laurmaedje** [comment]
@flyingmutant I'll make one later today.

**Comment by laurmaedje** [comment]
@flyingmutant I've just released ecow 0.1.2.
